name: Hello World

on:
  push: {branches: jaya-patch-1}
  pull_request: {branches: jaya-patch-1}

jobs:
  test:
    runs-on: ubuntu-latest 
    name: Install external repo
    steps:
      - uses: actions/checkout@v2
      - run: node index.js
