Name: Hello World

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest 
    name: Install external repo
    steps:
      - name: Obtain a GitHub App Installation Access
        id: githubAppAuth
      - run: node index.js
