name: Hello World

on:
  push: {branches: main}
  pull_request: {branches: main}

jobs:
  test:
    runs-on: ubuntu-latest 
    name: Install external repo
    steps:
      - uses: actions/checkout@v2
        with:
          repository: lbg-cloud-platform/apigeex-deployment-scripts
          ref: main
          token:  ${{ secrets.secret2 }}
          path: './place/to/clone/repo/into/jaya/'
