name: Hello World

on:
  push: {branches: jaya-node-patch1}
  pull_request: {branches: jaya-node-patch1}

jobs:
  test:
    runs-on: ubuntu-latest 
    name: Install external repo
    steps:
      - uses: actions/checkout@v2
      - run: node index.js
      - run: npm list
